### ISSUE TITLE
Sankey (flow) not working for me

### ISSUE THREAD

**Issue by ataylan** [mstr-dev/Visualization-Plugins#1]
Before I mention the issue , I am very excited what MicroStartegy is doing with D3, hopefully it will be a game changer. 
I have followed the instructions and make all the custom viz work in MicroStartegy desktop 10. But D3 flow/Sankey shows white screen no viz. Anybody else having the same issue?

Thanks

**Comment by KanZhu** [comment]
Thanks very much for your feedback! We will try to figure out your case! Currently, it is not stably reproducible on our side yet. Does anyone know the trigger?

**Comment by plutoshaka** [comment]
Hi ataylan, one of us run into a similar problem.  Her problem is that we use an external JQuery library which is provided by Google and she failed to load it.  My suggestion is you comment out D3Flow line 23 with "//" at beginning and deleted "//" in line 22.  Line 22 provides a http version library which is not provided by Google.  Or you can also try using a VPN.

If you are in US, your problem probably has another cause, but just have a try first.

**Comment by ataylan** [comment]
Thank you KanZhu . plutoshaka I tried your suggestion but no luck. I downloaded the libraries and gave them internal links to eliminate any browser or security issues but no change. Some other viz examples are using similar libraries which are working for me. Thanks for suggestions

**Comment by sntrao** [comment]
Are these plugins supposed to work with v9.4.1 Web? I deployed them to v9.4.1 web plugins folder, but I get a javascript error:

JavaScript compile error:

File: ../javascript/mojo/js/source/VisBase.js

Warning: Javascript class not found:
mstrmojo.VisBase

JavaScript compile error:

File: ../plugins/SequenceSunburst/javascript/../javascript/mojo/js/source/CustomVisBase.js

Error: Cannot read property 'ui' of undefined

Warning: Javascript class not found:
mstrmojo.plugins.SequenceSunburst.CustomVisBase

**Comment by fengATmstr** [comment]
Hi, @sntrao. I afraid that this feature is not supported in 941. Maybe you can take a look at MicroStrategy 10 Desktop.

**Comment by QinMing** [comment]
Hi @fengATmstr , I adopted the D3Flow.js into mstr 9.4.1. The DOM elements seems like correctly rendered. I can find ".svg" and ".g" elements in the page's HTML source code. But they just don't show up in the page. Maybe they are transparent? Does 941 have different way to load .css? Or it's just that 941 doesn't support D3 plugins?
Thank you!

**Comment by fengATmstr** [comment]
Hi @QinMing, @sntrao  the visualizations in this repo do use 10 API. There is a way to get D3 visualizations for 9.4.1 documents(not VI). I found a [post](http://community.microstrategy.com/t5/MicroStrategy-Software/Integrating-3rd-party-javascript-visualizations-into-a/m-p/234900#M6176) in our community that may help you.  
Well, new tools and new APIs make it significantly easier to integrate plugins in 10. We encourage you to upgrade to get all 10 new features.
Thanks

**Comment by nitishmathew** [comment]
I tried D3Flow.js in 10 it it works like a charm!

**Comment by QinMing** [comment]
Thanks @fengATmstr !
But @nitishmathew , the D3Flow.js work on my v10 **web**, but doesn't work on v10 **desktop**. Have you tried it on desktop? 
Oh, this is exactly the same issue mentioned by @ataylan 

BTW: I adopted it into v9.4.1 web and it works perfectly. It was a little bit tricky.

=====Update=====
I'm in the same situation as ataylan. Changing the URLs doesn't improve anything. Maybe there is some other differences between desktop and web? I hope this will be resolved.

**Comment by nitishmathew** [comment]
Hi Min,

I haven’t tried it on Desktop.

-Nitish

**Comment by fengATmstr** [comment]
@QinMing @ataylan This issue on Desktop is reproduced. The cause of the issue is the addressing strategy for external lib of Desktop is different from Web. We will check in the fix soon.

Thanks guys.

**Comment by plutoshaka** [comment]
Hi all, the root cause of this problem is that something goes wrong when _LoadsScript handles local files as external library for OneTier.  This has to be fixed in the next hotfix.  I just changed the local sankey file as an online external library as a temporary solution and have uploaded the new version.  You can download and have a try.  Sorry for the inconvenience.
