### ISSUE TITLE
Sequence Sunburst viz is cut off 

### ISSUE THREAD

**Issue by ataylan** [mstr-dev/Visualization-Plugins#10]
when I use the sequence sunburst viz The vis appears cut off it does not center it properly. Thanks to you guys Sankey works too but sometimes the bottom part is also slightly cut off. Anything I can do to fix this?

**Comment by KanZhu** [comment]
Hi ataylan, did you encounter this issue in Visual insight dashboard? We reproduced it only in VI and want to confirm with you.

**Comment by ataylan** [comment]
I encountered this on MicroStrategy desktop 10.  My web server is in another machine and it is 9.41
I don't have JavaScript d3 viz there.
I hope I answered your question

**Comment by KanZhu** [comment]
Yeah, got it! That is the case we verified. We will try to fix it soon.

**Comment by KanZhu** [comment]
This issue should be fixed now. Pls try the newest version. I will close it first. If you encounter it again, pls let us know.
