### ISSUE TITLE
D3Flow errors on MSTR AWS

### ISSUE THREAD

**Issue by abusto** [mstr-dev/Visualization-Plugins#113]
Hi All,

I am trying to implement the D3Flow visualization in a MSTR AWS (Amazon WebServices) but I get a bunch of errors. The errors com from:
https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js
html2canvas.js?v=-2018184671

Our environment uses AWS with Single sing On (SSO), is there anything extra we need to configure for AWS?

I get many errors, but here are the main ones:
d3.min.js:1 Error: Invalid value for <path> attribute d="M36,NaNC171.5,NaN 171.5,334.28302594625495 307,334.28302594625495"o @ d3.min.js:1(anonymous function) @ d3.min.js:3Y @ d3.min.js:1_a.each @ d3.min.js:3_a.attr @ d3.min.js:3mstrmojo.plugins.D3Flow.D3Flow.mstrmojo.declare.plot @ D3Flow.js:201renderVisualization @ VM13120:1(anonymous function) @ VM13120:1A.onload @ mojo-oivm.js?v=-2018184671:1
d3.min.js:1 Error: Invalid negative value for <rect> attribute height="-0.5702561697647639"o @ d3.min.js:1(anonymous function) @ d3.min.js:3Y @ d3.min.js:1_a.each @ d3.min.js:3_a.attr @ d3.min.js:3mstrmojo.plugins.D3Flow.D3Flow.mstrmojo.declare.plot @ D3Flow.js:229renderVisualization @ VM13120:1(anonymous function) @ VM13120:1A.onload @ mojo-oivm.js?v=-2018184671:1
html2canvas.js?v=-2018184671:1015 Error: Invalid value for <path> attribute d="M36,NaNC171.5,NaN 171.5,425.3532916952961 307,425.3532916952961"createWindowClone @ html2canvas.js?v=-2018184671:1015renderDocument @ html2canvas.js?v=-2018184671:894window.html2canvas @ html2canvas.js?v=-2018184671:881(anonymous function) @ mstrLocalStorage.js?v=-2018184671:1
html2canvas.js?v=-2018184671:1015 Error: Invalid negative value for <rect> attribute height="-0.5702561697647639"createWindowClone @ html2canvas.js?v=-2018184671:1015renderDocument @ html2canvas.js?v=-2018184671:894window.html2canvas @ html2canvas.js?v=-2018184671:881(anonymous function) @ mstrLocalStorage.js?v=-2018184671:1

Thanks,
Armando

**Comment by PeipeiChen** [comment]
Hi Armando,

Thanks for reporting the issue. We are trying to reproduce your issue in house. Would you mind providing more detailed information?

For the MSTR AWS (Amazon WebServices), do you refer to the MSTR Analytics Enterprice we have on AWS marketplace(e.g.[ MicroStrategy Analytics Enterprise with SQL Server Standard ](https://aws.amazon.com/marketplace/pp/B00JK1ZEK6/ref=srh_res_product_title?ie=UTF8&sr=0-2&qid=1457405130959) )?

We notice that the error message indicates invalid value for attribute. Would you please provide the dataset used for this case?

Also, would you please provide a screenshot of the visualization where you encountered the error? This will help us to debug the error.

Thanks,
Emma

**Comment by abusto** [comment]
Hi Emma,

I think I solved the problem. I had too many data points and the space was too small. If I increase the size of the display area it works fine. 

It would be nice to have it to automatically re-size to a readable level.

Quick question, can we control colors from MSTR for the D3Flow?

**Comment by PeipeiChen** [comment]
Hi Armando,

Currently, we are working on the new API for custom visualizations to control color from MSTR. It is coming soon. 

Thanks,
Emma

**Comment by abusto** [comment]
Perfect, thanks.
