### ISSUE TITLE
MSTR Analytics Desktop

### ISSUE THREAD

**Issue by CPoderoso** [mstr-dev/Visualization-Plugins#13]
Hi,

I tried to put the plugins at C:\Program Files (x86)\MicroStrategy\Client\resources\webapp\plugins but it does not work.

Do you know how I can use it in Desktop Analytics?

Thanks!

**Comment by alexisrolland** [comment]
The correct path for Microstrategy v10 Desktop is actually:
C:\Program Files (x86)\MicroStrategy\MicroStrategy Desktop\code\plugins

Hope it helps

**Comment by deekookee** [comment]
Thanks @alexisrolland 
@CPoderoso is your problem resolved?

**Comment by CPoderoso** [comment]
Yes! Great. It is working now.

Thanks!
