### ISSUE TITLE
Zoomable sunburst not working

### ISSUE THREAD

**Issue by Trinadhbabu** [mstr-dev/Visualization-Plugins#136]
Hello all,

I am trying to build zoomable sunburst(http://bl.ocks.org/mbostock/4348373) visualization in mstr. Its working fine with sample data provided in the example, but when Implement the same with MSTR data using **var json = this.dataInterface.getRawData(mstrmojo.models.template.DataInterface.ENUM_RAW_DATA_FORMAT.TREE);**
 its showing root 0 for me. Any solution for this kind of issue? please find the attached code.
[Zoom.txt](https://github.com/mstr-dev/Visualization-Plugins/files/246331/Zoom.txt)

**Comment by Trinadhbabu** [comment]
Its working now. A small change in the variable makes my code work.

**Comment by vineelpatnana** [comment]
Can you share the zip file for zoomable sunburst chart in Microstrategy ?
