### ISSUE TITLE
ESRI Maps no drawn when D3 Flow is enabled in IE11

### ISSUE THREAD

**Issue by nate-downs** [mstr-dev/Visualization-Plugins#25]
I've had this issue for a few months now.  In IE11 when the D3 Flow visualization is enabled, the ESRI Maps will not draw or shade the outlines of states/counties/etc. I believe this is due to the fact the ESRI maps and D3 Flow visualization use the same 'path' definition in the CSS file. This does work in Chrome.

**Comment by KanZhu** [comment]
Thanks for reporting this issue. It was encountered and fixed previously. We added .custom-vis-layout.d3flow before all the CSS class, such as path and so forth. You can try the latest D3 Flow chart and the issue should be fixed already. BTW, you would need to clear your browser cache to apply the new CSS code of this Viz. I will close this issue first. Feel free to let us know, if it doesn't work on your side.
