### ISSUE TITLE
[DE19464] - Some plugins don't work as widgets in RSD. 

### ISSUE THREAD

**Issue by PeipeiChen** [mstr-dev/Visualization-Plugins#42]
The plugins that don't work in RSD include

ClusterDendrogram_Cartesian
ClusterDendrogram_Radial
CollapsibleIndentedTree
ReingoldTilfordTree_Cartesian
ReingoldTilfordTree_Radial
Interactive_Tree
D3ZoomableCirclePacking
SimpleGantt

[Reproduce steps]
1. download the latest version of the plugins from Gitsite.
2. deploy the plugins in the web server and restart the web server.
3. create a document and add a dataset.
4. add the dataset into the document's detail header section - > RMC on the grid - > go to Formatting and Properties - > Widgets -> DHTML - > select the plugin and apply.
![gitsite01](https://cloud.githubusercontent.com/assets/12961339/9725057/1030b370-5613-11e5-8f84-8c9b1abc5ce7.png)

Go to document's presentation mode.

Notice that an error message will pop out.
![de19464](https://cloud.githubusercontent.com/assets/12961339/9725063/26c4a240-5613-11e5-9dea-c55f029fa7cd.png)

**Comment by PeipeiChen** [comment]
The problem is that those plugins were created with the old version of VisBuilder. Even if we enable the option "Available for Reports" and "Available for document", they are actually not enabled for reports and documents.
![gitsite02](https://cloud.githubusercontent.com/assets/12961339/9725504/09c2a924-55de-11e5-8727-dd9ccbcf073e.png)

We have fixed this issue in the latest version of VisBuilder. Will keep it updated on [MSDL](https://lw.microstrategy.com/msdz/MSDL/10/docs/projects/VisSDK_All/default.htm#topics/Introduction_to_the_Visualization_SDK.htm) soon. 
We are working on those plugins as well to make them available for reports and documents.

**Comment by ffniu** [comment]
If this error occurs, could have this try.
Modify File  ***\WEB-INF\xml\styleCatalog.xml, add these two lines: < ActualParameter name="documentStyle" type="1" value="RWGridJsonStyle" /> < ActualParameter name="reportXMLStyle" type="1" value="VisualizationDataStyle />"

**Comment by PeipeiChen** [comment]
Fang has fixed the issue. Now below plugins can work in RWD. 
ClusterDendrogram_Cartesian
ClusterDendrogram_Radial
CollapsibleIndentedTree
ReingoldTilfordTree_Cartesian
ReingoldTilfordTree_Radial
Interactive_Tree
D3ZoomableCirclePacking
SimpleGantt

**Comment by PeipeiChen** [comment]
With the latest VisBuilder in this Repo, newly created plugin will work in RWD and report if we enable option "Available for reports" and "Available for documents".
