### ISSUE TITLE
[SimpleGantt]the plugin doesn't work in MSTR10.1.

### ISSUE THREAD

**Issue by PeipeiChen** [mstr-dev/Visualization-Plugins#53]
My dataset looks like this.
![simple gantt](https://cloud.githubusercontent.com/assets/12961339/9809795/f6124b10-589d-11e5-9ba4-7cb319834e31.png)

When I apply Simple Gantt in the dashboard, the chart doesn't render. Anyone knows what could be the problem? 
![simpegantt](https://cloud.githubusercontent.com/assets/12961339/9811000/16779d02-58a7-11e5-91ba-63bf64545a15.png)

**Comment by japerron** [comment]
Even though the visualization does not either require it or use it, the data will not be graphed unless a metric (any metric, including RowCount) is dragged onto the Metrics pane. Would you mind updating the readme/usage?

**Comment by PeipeiChen** [comment]
Thanks a lot for your answer, Antonio! It works after I add one metric. I will update the readme/usage accordingly.
