### ISSUE TITLE
D3Flow (sankey) not rendering on iPad

### ISSUE THREAD

**Issue by japerron** [mstr-dev/Visualization-Plugins#83]
Have deployed the 10.1 mobilebase plugin and have a number of d3 visualizations rendering properly on iPad. Is there anything that needs to be done to this vis to make it render on iPads as well?

There are a number of these visualizations in this scenario, I am particularly interested in the D3Flow one.

Thanks

**Comment by yue-zhang** [comment]
We will take a look at this issue and get back to you later.

**Comment by yue-zhang** [comment]
This is indeed an issue with our 10.1 mobile client. We have addressed this issue in our 10.2 Mobile and please wait for 10.2 release (Nov 30th).
