### ISSUE TITLE
_VisBuilder Error unsupported major minor version 52	

### ISSUE THREAD

**Issue by MSTRMOJO** [mstr-dev/Visualization-Plugins#85]
_VisBuilder error ..../VisBuilderPageComponent unsupported major minor version 52

**Comment by ffniu** [comment]
This error was caused by the JDK compiler version  incompatibility. Now using JDK1.7 can work and classes have been pushed up.

**Comment by PeipeiChen** [comment]
The error is gone with the latest version.
