### ISSUE TITLE
SequenceBurst: Cannot read property 'galleryPanel' of undefined

### ISSUE THREAD

**Issue by arhmnsh** [mstr-dev/Visualization-Plugins#9]
I'm using 1 attribute and a metric. When I run the document, I get this error:

TypeError:
SequenceBurst: Cannot read property 'galleryPanel' of undefined

![image](https://cloud.githubusercontent.com/assets/1363724/8403894/606b58a8-1e51-11e5-99d8-f6a9efdc5ac2.png)

**Comment by KanZhu** [comment]
Hi arhmnsh,

Thanks for your issue reporting! We have reproduced it inhouse. It is scheduled with high priority. Will keep you posted when it is fixed! 

Best,
Kan

**Comment by plutoshaka** [comment]
Hi arhmnsh, please try newest version of sunburst, it should be free of this error message.

**Comment by KanZhu** [comment]
I will close it first. If you encounter it again, pls let us know.
