### ISSUE TITLE
Vis Builder Plug-in not working

### ISSUE THREAD

**Issue by ckiefer** [mstr-dev/Visualization-Plugins#91]
The latest Visualization Builder plug-in from the repo throws an error: "Cannot read property 'indexOf' null":

![vis_builder_plugin](https://cloud.githubusercontent.com/assets/8458235/11065353/1d2ba972-87c3-11e5-833a-e4381554c32b.jpg)

MSTR Web is running on Tomcat. MSTR version 10.1, HF 1.

**Comment by PeipeiChen** [comment]
Hi, please have a try with latest commit we posted. It should be working well on both 10.1 and 10.2.

**Comment by ckiefer** [comment]
Hi
Yes, the latest plug-in works. Thanks for the support.
